services:
  frontend:
    build:
      context: ./
      target: frontend
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /usr/local/app/src
        - path: ./frontend/package.json
          action: rebuild

  backend:
    build:
      context: ./
      target: backend
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: rekredo
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild

  mysql:
    image: mysql:9.3
    volumes:
      - rekredo:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rekredo
    ports:
      - '3306:3306'

volumes:
  rekredo:
